name: Elixir CI

on:
  push:
    branches: 
      - master
  pull_request:

env:
  MIX_ENV: test

steps:
  - uses: actions/checkout@v2
  - name: Read .tool-versions
    uses: marocchino/tool-versions-action@v1
    id: versions
  - name: Set up Elixir
    uses: erlef/setup-elixir@v1
    with:
      elixir-version: ${{steps.versions.outputs.elixir}}
      otp-version: ${{ steps.versions.outputs.erlang}}
  - name: Install dependencies
    run: mix deps.get
  - name: Check Formatting
    run: mix format --check-formatted
  - name: Check Compile Warnings
    run: mix compile --warnings-as-errors --all-warnings
  - name: Run tests
    run: mix test
  # - name: Check Dialyzer
  #   run: mix dialyzer
  # - name: Check Credo Warnings
  #   run: mix credo --strict --only warning --ignore Consistency
